# Portions borrowed from https://jasonmccreary.me/articles/install-apache-php-mysql-macos-docker-local-development/
# PHP + Apache
FROM node:16.2
EXPOSE 3000

WORKDIR /app

COPY ./docker/npmrc_readonly /root/.npmrc
COPY ./docker/react-run.sh /setup/

CMD ["/bin/bash", "-c", "/setup/react-run.sh"]
